scheduler_db = './db-stash/scheduler.db'
collector_db = './db-stash/collector.db'
config_table = 'gw_config'
scheduler_table = 'gw_jobs'

iface='wlan0'
collector_iface = 'wlan0'
collector_tx_threshold = -69
ap_start = './scripts/ap-start.sh'
ap_stop = './scripts/ap-stop.sh'
scheduler = './gw-scheduler'
collector = './gw-collector'
channel_hopper = './gw-channel-hopper'
hostapd_conf = './conf/hostapd.conf'
dnsmasq_conf = './conf/dnsmasq.conf'
