#!/usr/bin/python

import config
import os
import time

while True:

    for channel in xrange(1,13):
    
        #print '[hopper] switching to channel %d' % channel
        os.system('iw dev %s set channel %d' % (config.collector_iface, channel))
        time.sleep(1)
